#Makefile generated by amake
#On Sat Jan 16 10:20:42 2016
#To print amake help use 'amake --help'.
CC=gcc
CPPC=g++
LINK=g++
SRCDIR=./src
OBJDIR=obj
FLAGS=-g -Wall -pthread -I/usr/include/libxml2 
LIBS=-lssl -lxml2 -ldl -lcrypto 
OBJS=$(OBJDIR)/connection.o $(OBJDIR)/nzb_file.o $(OBJDIR)/settings.o $(OBJDIR)/main.o $(OBJDIR)/www.o $(OBJDIR)/notify.o $(OBJDIR)/sig.o $(OBJDIR)/nzb.o $(OBJDIR)/yDec.o 
EXEC=myNZB
DATE=$(shell date +"%Y-%m-%d")

$(EXEC) : $(OBJS)
	$(LINK) $(OBJS) -o $(EXEC) $(FLAGS) $(LIBS)

$(OBJDIR)/connection.o: src/connection.cpp src/connection.h src/settings.h $(OBJDIR)/__setup_obj_dir
	$(CPPC) $(FLAGS) ./src/connection.cpp -c -o $@

$(OBJDIR)/nzb_file.o: src/nzb_file.cpp src/nzb_file.h src/settings.h src/utils.h $(OBJDIR)/__setup_obj_dir
	$(CPPC) $(FLAGS) ./src/nzb_file.cpp -c -o $@

$(OBJDIR)/settings.o: src/settings.cpp src/settings.h $(OBJDIR)/__setup_obj_dir
	$(CPPC) $(FLAGS) ./src/settings.cpp -c -o $@

$(OBJDIR)/main.o: src/main.cpp src/settings.h src/connection.h src/nzb.h \
 src/nzb_file.h src/notify.h src/sig.h src/utils.h src/www.h $(OBJDIR)/__setup_obj_dir
	$(CPPC) $(FLAGS) ./src/main.cpp -c -o $@

$(OBJDIR)/www.o: src/www.cpp src/www.h src/settings.h src/mt.h src/connection.h \
 src/utils.h $(OBJDIR)/__setup_obj_dir
	$(CPPC) $(FLAGS) ./src/www.cpp -c -o $@

$(OBJDIR)/notify.o: src/notify.cpp src/notify.h src/settings.h $(OBJDIR)/__setup_obj_dir
	$(CPPC) $(FLAGS) ./src/notify.cpp -c -o $@

$(OBJDIR)/sig.o: src/sig.cpp src/sig.h src/settings.h $(OBJDIR)/__setup_obj_dir
	$(CPPC) $(FLAGS) ./src/sig.cpp -c -o $@

$(OBJDIR)/nzb.o: src/nzb.cpp src/nzb.h src/utils.h src/connection.h src/settings.h \
 src/mt.h src/yDec.h src/connmgr.h src/shared_ptr.h src/sig.h \
 src/res_pool.h src/www.h $(OBJDIR)/__setup_obj_dir
	$(CPPC) $(FLAGS) ./src/nzb.cpp -c -o $@

$(OBJDIR)/yDec.o: src/yDec.cpp src/yDec.h src/settings.h $(OBJDIR)/__setup_obj_dir
	$(CPPC) $(FLAGS) ./src/yDec.cpp -c -o $@

$(OBJDIR)/__setup_obj_dir :
	mkdir -p $(OBJDIR)
	touch $(OBJDIR)/__setup_obj_dir

.PHONY: clean bzip release

clean :
	rm -rf $(OBJDIR)/*.o
	rm -rf $(EXEC)

bzip :
	tar -cvf "$(DATE).$(EXEC).tar" $(SRCDIR)/* Makefile
	bzip2 "$(DATE).$(EXEC).tar"

release : FLAGS +=-O3 -D_RELEASE
release : $(EXEC)

